name: deploy
on:
  push:
    branches:
      - main 
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - name: Install TuringPlugins
        run: |
          git clone https://github.com/Fifth-Space/mkdocs_plugins.git
          cd mkdocs_plugins
          pip install -e .
          cd ..
      - run: mkdocs gh-deploy --force
